jobs:
  build:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true
      - codecov/upload:
          file: cover-source.out
          token: bd25b822-dfeb-42ce-a905-dd1925e75b59    
orbs:
  go: circleci/go@1.5.0
  codecov: codecov/codecov@1.1.3
version: 2.1
workflows:
  main:
    jobs:
      - build