jobs:
  build:
    executor:
      name: go/default
      tag: '1.15'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true
      - codecov/upload:
          file: cover-source.out
  build-container:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: tufin/oasdiff
          tag: latest
      - docker/push:
          digest-path: /tmp/digest.txt
          image: tufin/oasdiff
          tag: latest
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"          
orbs:
  go: circleci/go@1.5.0
  codecov: codecov/codecov@1.1.3
  docker: circleci/docker@1.5.0
version: 2.1
workflows:
  main:
    jobs:
      - build
      - build-container